---
- name: apply common configuration to all nodes
  hosts: all
  gather_facts: false
  roles:
    - role: common

- name: start seaweedfs master service
  hosts: masters
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: weed-master

- name: start seaweedfs volume service
  hosts: volumes
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: weed-volume

- name: start seaweedfs filer service
  hosts: filers
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: weed-filer

- name: start seaweedfs s3 service
  hosts: s3s
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: weed-s3