---
- name: install the some useful tools
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - parted
   - curl
   - atop
   - sysstat
   - daemonize
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"