---
- name: create seaweedfs master directory
  file:
    path: "{{ mdir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: start seaweedfs master service
  poll: 0
  async: 10
  args:
      chdir: "{{ workdir }}"
      executable: /bin/bash
  shell: "nohup weed -v={{ loglevel }} -logdir={{ logdir }} master -mdir={{ mdir }} -ip={{ ansible_enp2s0f0.ipv4.address }} -port={{ masterPort }} -metrics.address={{ metrics.address }} -metrics.intervalSeconds={{ metrics.intervalSeconds }} -defaultReplication={{ defaultReplication }} -peers={{ peers }} > /dev/null 2>&1 &"

- name: debug master command message
  debug:
    msg: "nohup weed -v={{ loglevel }} -logdir={{ logdir }} master -mdir={{ mdir }} -ip={{ ansible_enp2s0f0.ipv4.address }} -port={{ masterPort }} -metrics.address={{ metrics.address }} -metrics.intervalSeconds={{ metrics.intervalSeconds }} -defaultReplication={{ defaultReplication }} -peers={{ peers }} > /dev/null 2>&1 &"